namespace NZWalks.API.Models.Domain
{
	public class Region
	{
		public Guid Id { get; set; }
		//The GUID data type is a 16 byte binary data type. This data type is used for the global identification of objects,
		//programs, records, and so on. The important property of a GUID is that each value is globally unique.
		//The value is generated by an algorithm, developed by Microsoft, which assures this uniqueness

		public string Code { get; set; }

		public string Name { get; set; }

		public double Area { get; set; }

		public double Lat { get; set; }

		public double Long { get; set; }

		public long Population { get; set; }

		//Navigation Property
		public IEnumerable<Walk> Walks { get; set; } //One region can have multipel Walks
	}
}
